<Project>
    <PropertyGroup>
        <ValheimGamePath>C:\Program Files (x86)\Steam\steamapps\common\Valheim</ValheimGamePath>
        <BepInExPath>$(ValheimGamePath)\BepInEx</BepInExPath>
        <CorlibPath>$(ValheimGamePath)\unstripped_corlib</CorlibPath>
        <AssembliesPath>$(ValheimGamePath)\Valheim_Data\Managed</AssembliesPath>
        <PublicizedAssembliesPath>$(AssembliesPath)\publicized_assemblies</PublicizedAssembliesPath>
        <CopyOutputDLLPath>C:\Users\peima\Desktop\VALHEIM MODDING\projects\PortalStations\PortalStations\Thunderstore</CopyOutputDLLPath>
        <AfterTargets>ILRepacker</AfterTargets>
    </PropertyGroup>
</Project>